mode: development
media_root: media
media_url: /media
base_url: http://headjs.com/
template: hyde.ext.jinja2
meta:
    twitter: http://twitter.com/headjs
    analytics: UA-20001309-1
    version: 0.96
    author: Tero Piirainen
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.blockdown.BlockdownPlugin
    - hyde.ext.plugins.markings.MarkingsPlugin
    - hyde.ext.plugins.markings.ReferencePlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.stylus.StylusPlugin
stylus:
    app: ~/local/bin/stylus
publisher:
    github:
        type: hyde.ext.publishers.dvcs.Git
        path: ../headjs.github.com
        url: git@github.com:headjs/headjs.github.com.git
        branch: master
